Conftab conftab[] = {
	{"nmach", &conf.nmach },
	{"nproc", &conf.nproc },
	{"npgrp", &conf.npgrp },
	{"npage0", &conf.npage0 },
	{"npage1", &conf.npage1 },
	{"npage", &conf.npage },
	{"nseg", &conf.nseg },
	{"nimage", &conf.nimage },
	{"npagetab", &conf.npagetab },
	{"nswap", &conf.nswap },
	{"nalarm", &conf.nalarm },
	{"nchan", &conf.nchan },
	{"nenv", &conf.nenv },
	{"nenvchar", &conf.nenvchar },
	{"npgenv", &conf.npgenv },
	{"nmtab", &conf.nmtab },
	{"nmount", &conf.nmount },
	{"nmntdev", &conf.nmntdev },
	{"nmntbuf", &conf.nmntbuf },
	{"nmnthdr", &conf.nmnthdr },
	{"nstream", &conf.nstream },
	{"nqueue", &conf.nqueue },
	{"nblock", &conf.nblock },
	{"nsrv", &conf.nsrv },
	{"nurp", &conf.nurp },
	{"nasync", &conf.nasync },
	{"npipe", &conf.npipe },
	{"maxialloc", &conf.maxialloc },
	{"base0", &conf.base0 },
	{"base1", &conf.base1 },
	{"copymode", &conf.copymode },
	{"ipif", &conf.ipif },
	{"ip", &conf.ip },
	{"arp", &conf.arp },
	{"frag", &conf.frag },
	{"cntrlp", &conf.cntrlp },
	{"dkif", &conf.dkif },
	{ 0, 0 },
};

