Conftab conftab[] = {
	{"nmach", &conf.nmach },
	{"nproc", &conf.nproc },
	{"npgrp", &conf.npgrp },
	{"npage0", &conf.npage0 },
	{"npage", &conf.npage },
	{"norig", &conf.norig },
	{"npte", &conf.npte },
	{"nmod", &conf.nmod },
	{"nalarm", &conf.nalarm },
	{"nchan", &conf.nchan },
	{"nenv", &conf.nenv },
	{"nenvchar", &conf.nenvchar },
	{"npgenv", &conf.npgenv },
	{"nmtab", &conf.nmtab },
	{"nmount", &conf.nmount },
	{"nmntdev", &conf.nmntdev },
	{"nmntbuf", &conf.nmntbuf },
	{"nmnthdr", &conf.nmnthdr },
	{"nstream", &conf.nstream },
	{"nqueue", &conf.nqueue },
	{"nblock", &conf.nblock },
	{"nsrv", &conf.nsrv },
	{"nnoifc", &conf.nnoifc },
	{"nnoconv", &conf.nnoconv },
	{"nurp", &conf.nurp },
	{"nasync", &conf.nasync },
	{"npipe", &conf.npipe },
	{"maxialloc", &conf.maxialloc },
	{"base0", &conf.base0 },
	{"base1", &conf.base1 },
	{ 0, 0 },
};

