Conftab conftab[] = {
	{"nmach", &conf.nmach },
	{"nproc", &conf.nproc },
	{"npage0", &conf.npage0 },
	{"npage1", &conf.npage1 },
	{"npage", &conf.npage },
	{"nimage", &conf.nimage },
	{"nswap", &conf.nswap },
	{"nenv", &conf.nenv },
	{"nenvchar", &conf.nenvchar },
	{"npgenv", &conf.npgenv },
	{"nstream", &conf.nstream },
	{"nqueue", &conf.nqueue },
	{"nsrv", &conf.nsrv },
	{"nurp", &conf.nurp },
	{"nasync", &conf.nasync },
	{"base0", &conf.base0 },
	{"base1", &conf.base1 },
	{"copymode", &conf.copymode },
	{"ipif", &conf.ipif },
	{"ip", &conf.ip },
	{"arp", &conf.arp },
	{"frag", &conf.frag },
	{"cntrlp", &conf.cntrlp },
	{"dkif", &conf.dkif },
	{ 0, 0 },
};

